# https://hub.docker.com/r/vinanrra/7dtd-server
version: '3.8'

services:
  7dtdserver:
    image: vinanrra/7dtd-server
    container_name: {container_name}
    environment:
      # documented here
      # https://github.com/vinanrra/Docker-7DaysToDie#parameters
      - START_MODE=1
      - VERSION=stable
      - PUID=1000 # your uid of your user
      - PGID=1000 # your gid of your user's group
      - TimeZone=Africa/Johannesburg
      - TEST_ALERT=YES
      #- ALLOC_FIXES=YES #Optional - Install ALLOC FIXES
    volumes:
      - ./data/serverfiles:/home/sdtdserver/serverfiles/ #Optional, serverfiles
      - ./data/7daystodie:/home/sdtdserver/.local/share/7DaysToDie/ #Optional, maps files
      - ./data/log:/home/sdtdserver/log/ #Optional, logs
      - ./data/backups:/home/sdtdserver/lgsm/backup/ #Optional, backups
      - ./data/lgsm-config:/home/sdtdserver/lgsm/config-lgsm/sdtdserver # Optional, alerts
    ports:
      - 26900:26900/tcp
      - 26900:26900/udp
      - 26901:26901/udp
      - 26902:26902/udp
      - 8080:8080/tcp
      - 8081:8081/tcp
      - 8082:8082/tcp
    restart: unless-stopped #NEVER USE WITH START_MODE=4 or START_MODE=0
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
